MODULE_big = blackhole_am

OBJS = blackhole_am.o

EXTENSION = blackhole_am
DATA = blackhole_am--1.0.sql
PGFILEDESC = "blackhole_am - template table AM eating all data"

REGRESS = blackhole_am

subdir = contrib/blackhole_am
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk