MODULE_big = blackhole_cplusplus

EXTENSION = blackhole_cplusplus
CXX_SRCS = blackhole_cplusplus.cc
DATA = blackhole_cplusplus--1.0.sql
OBJS = $(CXX_SRCS:.cc=.o)
PGFILEDESC = "blackhole_cplusplus - Minimal extension template in C++"

subdir = contrib/blackhole_cplusplus
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
